### ISSUE TITLE
Review the project structure

### ISSUE THREAD

**Issue by prenc** [Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-algorithm#1]

**Comment by mslazynski** [comment]
Przejrzałem aktualną dokumentację Julii plus powiązane dyskusje (przede wszystkim https://github.com/JuliaLang/julia/issues/4600). Long story short: w Julii 0.7 "poprawili" system modułów i teraz jest diablo irytujący, i trochę szkoda słów, więc nie będę poświęcał tego postu na narzekanie :)

Aktualna struktura jest w porządku, nie da się tego zrobić lepiej w aktualnej wersji Julii.
